# Generated by Django 4.1.8 on 2023-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hkd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertcontact",
            name="email",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="alertcontact",
            name="name",
            field=models.TextField(),
        ),
    ]
