# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    user: "$UID:$GID"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./containers/postgres/data/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  grafana:
    container_name: grafana
    # Alpine by default
    image:  grafana/grafana-oss:9.4.7
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      # Use to init provisionning
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - ./containers/grafana/data/:/var/lib/grafana
      - ./containers/grafana/config.ini:/usr/local/etc/grafana/grafana.ini
      - ./containers/grafana/provisioning:/etc/grafana/provisioning

  influxdb:
    container_name: influxdb
    image: influxdb:2.6-alpine
    user: "$UID:$GID"
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - '8086:8086'
    volumes:
      - ./containers/influxdb/data/:/var/lib/influxdb
      - ./containers/influxdb/scripts:/docker-entrypoint-initdb.d
  apache:
    container_name: apache
    image: httpd:alpine3.17
    user: "$UID:$GID"
    ports:
    - '8080:80'
    # volumes:
      # - ./containers/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf