# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:10.23-alpine
    user: "$UID:$GID"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./containers/postgres/data/:/data/postgres
    ports:
      - "5432:5432"

  grafana:
    container_name: grafana
    # Alpine by default
    image:  grafana/grafana-oss:9.4.7
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      # Use to init provisionning
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - ./containers/grafana/data/:/var/lib/grafana
      - ./containers/grafana/config.ini:/etc/grafana/grafana.ini
      - ./containers/grafana/provisioning:/etc/grafana/provisioning

  influxdb:
    container_name: influxdb
    image: influxdb:2.7-alpine
    user: "$UID:$GID"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - '8086:8086'
    volumes:
      - ./containers/influxdb/data/:/var/lib/influxdb
      - ./containers/influxdb/scripts:/docker-entrypoint-initdb.d
  apache:
    container_name: apache
    image: httpd:alpine3.17
    user: "$UID:$GID"
    ports:
    - '8080:80'
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:21.1.1
    user: "$UID:$GID"
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: $KEYCLOAK_CREATE_ADMIN_USER
      KEYCLOAK_ADMIN_USER: $KEYCLOAK_ADMIN_USER
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KEYCLOAK_MANAGEMENT_USER: $KEYCLOAK_MANAGEMENT_USER
      KEYCLOAK_MANAGEMENT_PASSWORD: $KEYCLOAK_MANAGEMENT_PASSWORD
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: $POSTGRES_DB
      KEYCLOAK_DATABASE_USER: $POSTGRES_USER 
      KEYCLOAK_DATABASE_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - postgres